import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
option_as_alt = "OnlyLeft"

[font]
size= 14.0


[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"


