[user]
name = "Julien Cheype"
email = "cheype@gmail.com"

[ui]
default-command = "log"

[revsets]
log = "::@"

[aliases]
sync = ['git', 'fetch', '--all-remotes']
evolve = ['rebase', '--skip-emptied', '-d']
xl = ['log', '-r', 'all()']

[git]
templates.git_push_bookmark = "jcheype/push-"
